Feature/customize emoji amount
Ryczko/Employee-pulse pull request #121
Opened 2023-03-29 15:26 UTC by a-lukasiewicz

2023-03-30 07:56 UTC, pmatyjasik commented
Fix mobile view under 350px

2023-03-30 08:52 UTC, a-lukasiewicz commented
> Fix mobile view under 350px <img alt="CleanShot 2023-03-30 at 09 57 48@2x" width="335" src="https://user-images.githubusercontent.com/73366069/228769250-fb65c5ae-e1dd-4e54-aedc-cb77aacce0f9.png">

Fixed

2023-03-30 08:53 UTC, pmatyjasik approved these changes

2023-03-30 15:41 UTC, Ryczko requested changes

2023-03-30 15:41 UTC, Ryczko commented on src/features/surveys/components/EmojiAdd/EmojiAdd.tsx
We shouldn't create a separate component for this element - too many similarities with a regular picker. We should just pass another callback to the classic picker

2023-04-07 19:05 UTC, Ryczko approved these changes

2023-04-07 19:11 UTC, merged