This pull request addresses the issue of Validation on answer page #124
Ryczko/Employee-pulse pull request #127
Opened 2023-03-31 21:34 UTC by phootako630

The changes I made include removing buttonDisable and adding a useState hook to get emoji error.

2023-03-31 21:44 UTC, phootako630 commented
It goes like this when users click the send button without selected icons:
![image](https://user-images.githubusercontent.com/114458211/229238436-19d72b7f-b0f2-47f8-8bb0-ea2504774c56.png)

2023-04-01 09:18 UTC, Ryczko requested changes
Great job! Thank you for your contribution 🎉
One small thing. Error should disappear when user selected emoji. Please add `setShowEmojiError(false);` to `handleIconClick` 😊

2023-04-01 14:56 UTC, phootako630 commented
Thanks for pointing out the problem. I will correct it asap.

2023-04-02 08:50 UTC, Ryczko approved these changes

2023-04-02 08:50 UTC, merged