Prepare account deletion
Ryczko/Employee-pulse pull request #67
Opened 2023-03-15 12:19 UTC by xdk78

Resolve #51

2023-03-15 17:01 UTC, Ryczko commented on src/layout/Navigation/Navigation.tsx
> +                      </Menu.Item>
What about burger menu?

2023-03-15 17:19 UTC, xdk78 commented on src/layout/Navigation/Navigation.tsx
> +                            Settings
what is cog?

2023-03-15 17:38 UTC, Ryczko commented on src/layout/Navigation/Navigation.tsx
> +                            Settings
![image](https://user-images.githubusercontent.com/51440879/225395913-9412d594-7f4e-4ad4-91f8-f9f31b8ede4d.png)

2023-03-19 11:48 UTC, Ryczko requested changes
3 problems has been found:

- [ ] Sometimes on my surveys page when you click delete button and then cancel on modal, all page is blocked (nothing can be clicked)

[screen-capture (1).webm](https://user-images.githubusercontent.com/51440879/226172975-e68925af-2eb8-4447-9015-c3b75a7e791c.webm)


- [ ] 'Delete my account' button jumps when modal is opened.

[screen-capture (2).webm](https://user-images.githubusercontent.com/51440879/226173066-36f3cddd-007f-4448-b9bd-70f99ff3e688.webm)


- [ ] When settings button is hover it should takes all width on mobile and desktop:
![image](https://user-images.githubusercontent.com/51440879/226173133-f33f5d2c-64ac-4b37-a7e8-4838aff0e6b3.png)
![image](https://user-images.githubusercontent.com/51440879/226173145-e5a96a43-6650-44fc-b598-8a8cc1744d50.png)

2023-03-19 22:51 UTC, pmatyjasik commented on src/pages/settings/index.tsx
> +      </Head>
You should add meta tag in Head component (Look on homepage file)

2023-03-19 22:51 UTC, pmatyjasik commented on src/pages/settings/index.tsx
> +        )}
Remove that error

2023-03-20 10:57 UTC, xdk78 commented on src/pages/settings/index.tsx
> +        )}
why?

2023-03-20 12:26 UTC, xdk78 commented on src/pages/settings/index.tsx
> +        )}
ok

2023-03-20 16:29 UTC, Ryczko approved these changes

2023-03-20 16:31 UTC, merged